ignored:
  - DL3008  # Specify version with `apt-get install -y <package>-<version>`
  - DL3013  # Pin versions in pip.
  - SC1091  # Not following: File not included in mock.
label-schema:
  org.opencontainers.image.authors: text
  org.opencontainers.image.description: text
  org.opencontainers.image.documentation: text
  org.opencontainers.image.source: text
  org.opencontainers.image.title: text
  org.opencontainers.image.vendor: text
  org.opencontainers.image.licenses: text
  org.opencontainers.image.url: text
  org.opencontainers.image.version: text
