name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - release/**

jobs:
  docker-lint:
    uses: finleyfamily/workflows/.github/workflows/docker.lint.yml@feat/docker-workflow
  docker-build:
    needs:
      - docker-lint
    uses: finleyfamily/workflows/.github/workflows/docker.build.yml@feat/docker-workflow
  spellcheck:
    uses: finleyfamily/workflows/.github/workflows/spellcheck.yml@master
